[package]
name = "geoecef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.1"
latlon = "0.1.3"
slint = "1.8.0"

[build-dependencies]
slint-build = "1.8.0"
